create extension if not exists "pgcrypto";

create table if not exists vehicles (
  id uuid primary key default gen_random_uuid(),
  brand text not null,
  model text not null,
  year integer not null,
  price numeric,
  type text,
  mileage text,
  power text,
  engine text,
  transmission text,
  color text,
  description text,
  image_url text,
  gallery jsonb default '[]'::jsonb,
  features jsonb default '{}'::jsonb,
  featured boolean default false,
  sold boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists leads (
  id uuid primary key default gen_random_uuid(),
  name text,
  phone text,
  source text,
  vehicle_id uuid references vehicles(id) on delete set null,
  message text,
  created_at timestamptz default now()
);

alter table vehicles enable row level security;
alter table leads enable row level security;

create policy "Public can read vehicles" on vehicles for select using (true);
create policy "Authenticated users manage vehicles" on vehicles for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Public can create leads" on leads for insert with check (true);
create policy "Authenticated users read leads" on leads for select using (auth.role() = 'authenticated');


-- V14 Plataforma profesional
alter table if exists vehicles add column if not exists commercial_status text default 'available';
create table if not exists leads (id uuid primary key default gen_random_uuid(), name text, phone text, vehicle_id uuid null, vehicle_label text, channel text, status text default 'new', notes text, created_at timestamptz default now());
create table if not exists finance_requests (id uuid primary key default gen_random_uuid(), name text, phone text, vehicle_id uuid null, vehicle_label text, estimated_price numeric, down_payment numeric, months integer, status text default 'pending', created_at timestamptz default now());
create table if not exists vehicle_events (id bigint generated by default as identity primary key, vehicle_id uuid null, event_type text not null, created_at timestamptz default now());
